openapi: 3.0.1
info:
  title: DEPA
  description: Specification for trust registry. 
  version: 2.0.0
servers:
- url: https://host:2020/depa/v2/registry/
  description: Registry APIs location
tags:
- name: Registry

paths:
  /fetch/policy:
    get:
      tags:
      - Registry
      summary: Get the common policies for dc/dp/cm.
      description: Get the common policies for dc/dp/cm.
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonPolicies'
        404:
          description: not found or to many records found.

  /fetch/{fiduciaryType}:
    post:
      tags:
      - Registry
      summary: Get the fiduciary details by the given parameters.
      description: Get the dp details.
      parameters:
        - name : fiduciaryType
          in : path
          required: true
          schema:
            type: string
            enum:
              - cm
              - dc
              - dp
      requestBody:
        content:
            application/json:
              schema:
                type: object
                properties:
                  fiduciaryName:
                    type: string
                  domain:
                    type: string
                  pkCertificate:
                    description: base64 encoded public key certificate of the fiduciary in JWK format.
                    type: string
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entity'
        404:
          description: not found or to many records found.


#--------------- SCHEMA DEFINITIONS -----------
components:
  schemas:

    CommonPolicies:
      type: object
      properties:
        cmPolicies:
          type: object
          allOf:
          - $ref: '#/components/schemas/PolicyDetails'
        dcPolicies:
          type: object
          allOf:
          - $ref: '#/components/schemas/PolicyDetails'
        dpPolicies:
          type: object
          allOf:
          - $ref: '#/components/schemas/PolicyDetails'
        ttl:
          description: caller can safely cache the response for the given time in min.
          type: integer
       
    PolicyDetails:
      type: object
      properties:
        policy:
          description: policy definition
          type: object
          allOf:
          - $ref: '#/components/schemas/PolicyDefinition'
        policy_createdBy:
          type: string
        policy_createdOn:
          type: string
          format: date-time

    PolicyDefinition:
      type: object
      properties:
        version:
          description: policy definition version
          type: string
        rules:
          type: array
          items:
            properties:
              effect:
                type: string
                enum:
                  - allow
                  - deny
              when:
                properties:
                  key:
                    type: string
                  operator:
                    type: string
                    enum:
                      - equal
                      - notEqual
                      - in
                      - like
                  value:
                    type: string

        rulesOperator:
          type: string
          enum:
            - allOf
            - anyOf

    Entity:
      type: object
      required:
        - name
        - domain
        - pkCertificate
      properties:
        name:
          type: string
        address:
          type: string
        domain:
          type: string
        website:
          type: string
        validFrom:
          type: string
          format: date-time 
        validUntil:
          type: string
          format: date-time
        pkCertificate:
          description: base64 encoded public key certificates in JWK format.
          type: array
          items:
            type: string
        registries:
          description: list of registries where this entity is listed.
          type: array
          items:
            type: string
        ttl:
          description: caller can safely cache the entry for the given ttl in min.
          type: integer
